/*
 * OpenAPI definition
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package romanow.abc.vkr.exam.model;

import java.util.Objects;

import com.google.gson.annotations.SerializedName;
import io.swagger.v3.oas.annotations.media.Schema;

import java.util.ArrayList;
import java.util.List;

/**
 * FullStudentBean
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2022-06-01T14:56:15.142+07:00[Asia/Novosibirsk]")
public class FullStudentBean {
  @SerializedName("student")
  private StudentBean student = null;

  @SerializedName("group")
  private FullGroupBean group = null;

  @SerializedName("studentRatings")
  private List<FullStudentRatingBean> studentRatings = null;

  public FullStudentBean student(StudentBean student) {
    this.student = student;
    return this;
  }

   /**
   * Get student
   * @return student
  **/
  @Schema(description = "")
  public StudentBean getStudent() {
    return student;
  }

  public void setStudent(StudentBean student) {
    this.student = student;
  }

  public FullStudentBean group(FullGroupBean group) {
    this.group = group;
    return this;
  }

   /**
   * Get group
   * @return group
  **/
  @Schema(description = "")
  public FullGroupBean getGroup() {
    return group;
  }

  public void setGroup(FullGroupBean group) {
    this.group = group;
  }

  public FullStudentBean studentRatings(List<FullStudentRatingBean> studentRatings) {
    this.studentRatings = studentRatings;
    return this;
  }

  public FullStudentBean addStudentRatingsItem(FullStudentRatingBean studentRatingsItem) {
    if (this.studentRatings == null) {
      this.studentRatings = new ArrayList<FullStudentRatingBean>();
    }
    this.studentRatings.add(studentRatingsItem);
    return this;
  }

   /**
   * Get studentRatings
   * @return studentRatings
  **/
  @Schema(description = "")
  public List<FullStudentRatingBean> getStudentRatings() {
    return studentRatings;
  }

  public void setStudentRatings(List<FullStudentRatingBean> studentRatings) {
    this.studentRatings = studentRatings;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    FullStudentBean fullStudentBean = (FullStudentBean) o;
    return Objects.equals(this.student, fullStudentBean.student) &&
        Objects.equals(this.group, fullStudentBean.group) &&
        Objects.equals(this.studentRatings, fullStudentBean.studentRatings);
  }

  @Override
  public int hashCode() {
    return Objects.hash(student, group, studentRatings);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class FullStudentBean {\n");
    
    sb.append("    student: ").append(toIndentedString(student)).append("\n");
    sb.append("    group: ").append(toIndentedString(group)).append("\n");
    sb.append("    studentRatings: ").append(toIndentedString(studentRatings)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
