/*
 * OpenAPI definition
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package romanow.abc.vkr.exam.model;

import java.util.Objects;

import com.google.gson.annotations.SerializedName;
import io.swagger.v3.oas.annotations.media.Schema;

import java.util.ArrayList;
import java.util.List;

/**
 * FullAnswerBean
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2022-06-01T14:56:15.142+07:00[Asia/Novosibirsk]")
public class FullAnswerBean {
  @SerializedName("answer")
  private AnswerBean answer = null;

  @SerializedName("task")
  private FullTaskBean task = null;

  @SerializedName("messages")
  private List<FullMessageBean> messages = null;

  public FullAnswerBean answer(AnswerBean answer) {
    this.answer = answer;
    return this;
  }

   /**
   * Get answer
   * @return answer
  **/
  @Schema(description = "")
  public AnswerBean getAnswer() {
    return answer;
  }

  public void setAnswer(AnswerBean answer) {
    this.answer = answer;
  }

  public FullAnswerBean task(FullTaskBean task) {
    this.task = task;
    return this;
  }

   /**
   * Get task
   * @return task
  **/
  @Schema(description = "")
  public FullTaskBean getTask() {
    return task;
  }

  public void setTask(FullTaskBean task) {
    this.task = task;
  }

  public FullAnswerBean messages(List<FullMessageBean> messages) {
    this.messages = messages;
    return this;
  }

  public FullAnswerBean addMessagesItem(FullMessageBean messagesItem) {
    if (this.messages == null) {
      this.messages = new ArrayList<FullMessageBean>();
    }
    this.messages.add(messagesItem);
    return this;
  }

   /**
   * Get messages
   * @return messages
  **/
  @Schema(description = "")
  public List<FullMessageBean> getMessages() {
    return messages;
  }

  public void setMessages(List<FullMessageBean> messages) {
    this.messages = messages;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    FullAnswerBean fullAnswerBean = (FullAnswerBean) o;
    return Objects.equals(this.answer, fullAnswerBean.answer) &&
        Objects.equals(this.task, fullAnswerBean.task) &&
        Objects.equals(this.messages, fullAnswerBean.messages);
  }

  @Override
  public int hashCode() {
    return Objects.hash(answer, task, messages);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class FullAnswerBean {\n");
    
    sb.append("    answer: ").append(toIndentedString(answer)).append("\n");
    sb.append("    task: ").append(toIndentedString(task)).append("\n");
    sb.append("    messages: ").append(toIndentedString(messages)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
