/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package romanow.abc.desktop;

import romanow.abc.core.constants.ConstValue;
import romanow.abc.core.entity.EntityList;

import java.awt.*;
import java.util.ArrayList;

/**
 *
 * @author romanow
 */
public class ListSelector extends javax.swing.JFrame {
    private ListBox box;
    private int idx;
    private I_ListSelected back;
    /**
     * Creates new form ListSelector
     */
    public ListSelector(int x0, int y0, String title, ArrayList<ConstValue> list, I_ListSelected ok0) {
        initComponents();
        setTitle(title);
        setVisible(true);
        setBounds(x0,y0,260,120);
        back = ok0;
        box = new ListBox(true,new Rectangle(10, 10, 220, 25), list, new I_ListSelected() {
            @Override
            public void onSelect(int idx0) {
                idx = idx0;
                }
            });
        add(box);
        }
    public ListSelector(int x0, int y0, String title, EntityList list, I_ListSelected ok0) {
        initComponents();
        setTitle(title);
        setVisible(true);
        setBounds(x0,y0,260,120);
        back = ok0;
        box = new ListBox(new Rectangle(10, 10, 220, 25), list, new I_ListSelected() {
            @Override
            public void onSelect(int idx0) {
                idx = idx0;
            }
        });
        add(box);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        OK = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(null);

        OK.setText("Выбрать");
        OK.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                OKActionPerformed(evt);
            }
        });
        getContentPane().add(OK);
        OK.setBounds(10, 44, 220, 25);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void OKActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_OKActionPerformed
        back.onSelect(box.getSelectedIndex());
        dispose();
    }//GEN-LAST:event_OKActionPerformed



    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton OK;
    // End of variables declaration//GEN-END:variables
}
