/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package romanow.abc.desktop;

import romanow.abc.core.Utils;
import romanow.abc.core.constants.ValuesBase;
import romanow.abc.core.entity.users.User;
import retrofit2.Response;

import javax.swing.*;
import java.awt.*;
import java.io.IOException;
import java.util.ArrayList;

/**
 *
 * @author romanow
 */
public class Login extends JFrame implements I_LogArea{
    private MainBaseFrame main;
    private I_Button back;
    /**
     * Creates new form Login
     */
    public Login(MainBaseFrame main0, I_Button back0) {
        main=main0;
        back = back0;
        initComponents();
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource(ValuesBase.env().applicationName(ValuesBase.AppNameIconPath)))); // NOI18N
        jLabel5.setText(ValuesBase.env().applicationName(ValuesBase.AppNameTitle));
        ClientIP.add("localhost");
        ClientIP.add("217.71.138.9");
        ClientIP.add("217.71.138.8");
        ClientIP.add("217.71.138.13");
        ClientIP.add("192.168.0.102");      // Для отладки - доступ через роутер = удаленный user
        Port.add("4567");
        Port.add("4569");
        Port.add("4571");
        Port.add("5001");
        setBounds(200,200,370,400);
        Login.setText("913*******");
        Password.setText("");
        main.setMES(LOG);
        setVisible(true);
        }

    public void setLoginName(String name){
        Login.setText(name);
        }
    public void setPassword(String name){
        Password.setText(name);
        }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        ClientON = new javax.swing.JCheckBox();
        ClientIP = new java.awt.Choice();
        Port = new java.awt.Choice();
        Login = new javax.swing.JTextField();
        Password = new javax.swing.JPasswordField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        LButton = new javax.swing.JButton();
        NewIP = new javax.swing.JTextField();
        AddIP = new javax.swing.JButton();
        LOG = new java.awt.TextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        ClientON.setText("Соединение");
        ClientON.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                ClientONItemStateChanged(evt);
            }
        });
        getContentPane().add(ClientON);
        ClientON.setBounds(230, 90, 110, 23);

        ClientIP.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                ClientIPItemStateChanged(evt);
            }
        });
        getContentPane().add(ClientIP);
        ClientIP.setBounds(130, 60, 120, 20);

        Port.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                PortItemStateChanged(evt);
            }
        });
        getContentPane().add(Port);
        Port.setBounds(130, 90, 90, 20);

        Login.setText("9139449081");
        getContentPane().add(Login);
        Login.setBounds(130, 120, 120, 25);

        Password.setText("pi31415926");
        Password.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                PasswordKeyPressed(evt);
            }
        });
        getContentPane().add(Password);
        Password.setBounds(130, 150, 120, 25);

        jLabel1.setText("Порт");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(20, 90, 60, 14);

        jLabel2.setText("Пароль");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(20, 150, 85, 14);

        jLabel3.setText("Сервер данных");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(20, 65, 100, 14);

        jLabel4.setText("Логин (телефон)");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(20, 120, 110, 14);

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel5.setText("Клиент сервера данных СНЭ");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(130, 20, 230, 20);

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/drawable/battery.png"))); // NOI18N
        jButton1.setBorderPainted(false);
        jButton1.setContentAreaFilled(false);
        getContentPane().add(jButton1);
        jButton1.setBounds(10, 10, 60, 50);

        LButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/drawable/login.png"))); // NOI18N
        LButton.setBorderPainted(false);
        LButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LButtonActionPerformed(evt);
            }
        });
        getContentPane().add(LButton);
        LButton.setBounds(260, 130, 40, 40);
        getContentPane().add(NewIP);
        NewIP.setBounds(130, 180, 120, 25);

        AddIP.setIcon(new javax.swing.ImageIcon(getClass().getResource("/drawable/add.png"))); // NOI18N
        AddIP.setBorderPainted(false);
        AddIP.setContentAreaFilled(false);
        AddIP.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/drawable/add.png"))); // NOI18N
        AddIP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddIPActionPerformed(evt);
            }
        });
        getContentPane().add(AddIP);
        AddIP.setBounds(260, 180, 40, 30);
        getContentPane().add(LOG);
        LOG.setBounds(20, 220, 320, 110);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ClientONItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_ClientONItemStateChanged
        if (ClientON.isSelected()){
            if (!main.startClient(ClientIP.getSelectedItem(),Port.getSelectedItem()))
                ClientON.setSelected(false);
            }
        else{
            disConnect();
            }
    }//GEN-LAST:event_ClientONItemStateChanged

    public void disConnect(){
        ClientON.setSelected(false);
        main.service=null;
        }



    private void LButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LButtonActionPerformed
        if (!ClientON.isSelected()){
            main.sendPopupMessage(this,LButton,"Произведите соединение с сервером");
            return;
            }
        try {
            Response<User> res = main.service.login(Login.getText(),new String(Password.getPassword())).execute();
            if (!res.isSuccessful()){
                main.sendPopupMessage(this,LButton,"Ошибка сервера: "+ Utils.httpError(res));
                return;
                }
            main.loginUser(res.body());
            main.debugToken = main.loginUser().getSessionToken();   // Токен новой сессии
            Response<ArrayList<String>>  serverEnv = main.service.getSetverEnvironment(main.debugToken).execute();
            if (!serverEnv.isSuccessful() || serverEnv.body()==null){
                main.onLoginSuccess();
                back.onPush();
                dispose();
                System.out.println("!!!!!! Сервер без проверки типа БД");
                return;
                }
            main.serverEnvironment = serverEnv.body();
            String ownSubjectArea = ValuesBase.env().applicationName(ValuesBase.AppNameSubjectArea);
            String serverSubjectArea = main.serverEnvironment.get(ValuesBase.AppNameSubjectArea);
            if (!serverSubjectArea.equals(ownSubjectArea)){
                main.sendPopupMessage(this,LButton,"Другой тип сервера: "+ serverSubjectArea);
                return;
                }
            main.onLoginSuccess();
            back.onPush();
            dispose();
            }catch (IOException ee){
                main.sendPopupMessage(this,LButton,"Ошибка сервера: "+ee.toString());
                }

    }//GEN-LAST:event_LButtonActionPerformed

    private void ClientIPItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_ClientIPItemStateChanged
        disConnect();
    }//GEN-LAST:event_ClientIPItemStateChanged

    private void PortItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_PortItemStateChanged
        disConnect();
    }//GEN-LAST:event_PortItemStateChanged

    private void PasswordKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_PasswordKeyPressed
        if(evt.getKeyCode()!=10) return;
        LButtonActionPerformed(null);
    }//GEN-LAST:event_PasswordKeyPressed

    private void AddIPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddIPActionPerformed
        ClientIP.add(NewIP.getText());
        NewIP.setText("");
    }//GEN-LAST:event_AddIPActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AddIP;
    private java.awt.Choice ClientIP;
    private javax.swing.JCheckBox ClientON;
    private javax.swing.JButton LButton;
    private java.awt.TextArea LOG;
    private javax.swing.JTextField Login;
    private javax.swing.JTextField NewIP;
    private javax.swing.JPasswordField Password;
    private java.awt.Choice Port;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;

    @Override
    public TextArea getLogArea() {
        return LOG;
    }
    // End of variables declaration//GEN-END:variables
}
