package romanow.abc.desktop;

import retrofit2.Call;
import romanow.abc.bridge.APICallSync;
import romanow.abc.bridge.ConsoleClient;
import romanow.abc.core.Utils;
import romanow.abc.core.constants.ValuesBase;
import romanow.abc.core.entity.users.User;
import retrofit2.Response;
import romanow.abc.exam.model.DisciplineBean;
import romanow.abc.exam.model.TeacherBean;

import javax.swing.*;
import java.awt.*;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;

/**
 *
 * @author romanow
 */
public class Login extends JFrame implements I_LogArea{
    private MainBaseFrame main;
    private I_Button back;
    private ConsoleClient emClient = new ConsoleClient();
    /**
     * Creates new form Login
     */
    public Login(MainBaseFrame main0, I_Button back0) {
        main=main0;
        back = back0;
        initComponents();
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource(ValuesBase.env().applicationName(ValuesBase.AppNameIconPath)))); // NOI18N
        jLabel5.setText(ValuesBase.env().applicationName(ValuesBase.AppNameTitle));
        ClientIP.add("localhost");
        ClientIP.add("217.71.138.9");
        ClientIP.add("217.71.138.8");
        ClientIP.add("217.71.138.13");
        ClientIP.add("217.71.129.139");      // Для отладки - доступ через роутер = удаленный user
        Port.add("4502");
        Port.add("4567");
        Port.add("4569");
        Port.add("4571");
        Port.add("5001");
        setBounds(200,200,370,480);
        Login.setText("romanov@corp.nstu.ru");
        Password.setText("password");
        main.setMES(LOG);
        setVisible(true);
    }

    public void setLoginName(String name){
        Login.setText(name);
    }
    public void setPassword(String name){
        Password.setText(name);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        ClientIP = new java.awt.Choice();
        Port = new java.awt.Choice();
        Login = new javax.swing.JTextField();
        Password = new javax.swing.JPasswordField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        LButton = new javax.swing.JButton();
        NewIP = new javax.swing.JTextField();
        AddIP = new javax.swing.JButton();
        LOG = new java.awt.TextArea();
        ConnectToServer = new javax.swing.JCheckBox();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        ClientIP.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                ClientIPItemStateChanged(evt);
            }
        });
        getContentPane().add(ClientIP);
        ClientIP.setBounds(130, 60, 120, 20);

        Port.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                PortItemStateChanged(evt);
            }
        });
        getContentPane().add(Port);
        Port.setBounds(130, 90, 120, 20);

        Login.setText("9139449081");
        getContentPane().add(Login);
        Login.setBounds(130, 120, 170, 25);

        Password.setText("pi31415926");
        Password.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                PasswordKeyPressed(evt);
            }
        });
        getContentPane().add(Password);
        Password.setBounds(130, 150, 120, 25);

        jLabel1.setText("Порт");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(20, 90, 60, 14);

        jLabel2.setText("Пароль");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(20, 150, 85, 14);

        jLabel3.setText("Сервер данных");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(20, 65, 100, 14);

        jLabel4.setText("Логин (телефон)");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(20, 120, 110, 14);

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel5.setText("Дистанционная сдача экзамена");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(80, 20, 270, 20);

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/drawable/lecture.png"))); // NOI18N
        jButton1.setBorderPainted(false);
        jButton1.setContentAreaFilled(false);
        getContentPane().add(jButton1);
        jButton1.setBounds(10, 10, 60, 50);

        LButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/drawable/login.png"))); // NOI18N
        LButton.setBorderPainted(false);
        LButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LButtonActionPerformed(evt);
            }
        });
        getContentPane().add(LButton);
        LButton.setBounds(260, 150, 40, 40);
        getContentPane().add(NewIP);
        NewIP.setBounds(130, 180, 120, 25);

        AddIP.setIcon(new javax.swing.ImageIcon(getClass().getResource("/drawable/add.png"))); // NOI18N
        AddIP.setBorderPainted(false);
        AddIP.setContentAreaFilled(false);
        AddIP.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/drawable/add.png"))); // NOI18N
        AddIP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddIPActionPerformed(evt);
            }
        });
        getContentPane().add(AddIP);
        AddIP.setBounds(80, 180, 40, 30);
        getContentPane().add(LOG);
        LOG.setBounds(20, 220, 320, 210);
        getContentPane().add(ConnectToServer);
        ConnectToServer.setBounds(260, 90, 40, 21);

        pack();
    }// </editor-fold>//GEN-END:initComponents



    @Override
    public TextArea getLogArea() {
        return LOG;
    }

    public void disConnect(){
        emClient.clear();
    }

    private void LButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LButtonActionPerformed
        emClient.clear();
        String answer = emClient.login(ClientIP.getSelectedItem(),Port.getSelectedItem(),Login.getText(),new String(Password.getPassword()));
        if (answer.length()!=0){
            System.out.println("Нет соединения с сервером:\n"+answer);
            return;
        }
        main.setClient(emClient);
        main.debugToken = emClient.getToken();   // Токен новой сессии
        main.loginUser.setTypeId(ValuesBase.UserAdminType);
        main.onLoginSuccess();
        back.onPush();
        dispose();
    }//GEN-LAST:event_LButtonActionPerformed

    private void ClientIPItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_ClientIPItemStateChanged
        //disConnect();
    }//GEN-LAST:event_ClientIPItemStateChanged

    private void PortItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_PortItemStateChanged
        //disConnect();
    }//GEN-LAST:event_PortItemStateChanged

    private void PasswordKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_PasswordKeyPressed
        if(evt.getKeyCode()!=10) return;
        LButtonActionPerformed(null);
    }//GEN-LAST:event_PasswordKeyPressed

    private void AddIPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddIPActionPerformed
        ClientIP.add(NewIP.getText());
        NewIP.setText("");
    }//GEN-LAST:event_AddIPActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AddIP;
    private java.awt.Choice ClientIP;
    private javax.swing.JCheckBox ConnectToServer;
    private javax.swing.JButton LButton;
    private java.awt.TextArea LOG;
    private javax.swing.JTextField Login;
    private javax.swing.JTextField NewIP;
    private javax.swing.JPasswordField Password;
    private java.awt.Choice Port;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    // End of variables declaration//GEN-END:variables
}
