/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package romanow.abc.desktop;

import java.awt.*;

/**
 *
 * @author romanow
 */
public class LogPanel extends BasePanel implements I_LogArea {

    /**
     * Creates new form TestPanel
     */
    public LogPanel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        MES = new java.awt.TextArea();

        setLayout(null);
        add(MES);
        MES.setBounds(10, 10, 910, 650);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private java.awt.TextArea MES;
    public TextArea mes(){ return MES; }

    @Override
    public void refresh() {

    }

    @Override
    public void eventPanel(int code, int par1, long par2, String par3, Object oo) {
        if (code==EventLogToFront){
            main.panelToFront(this);
            popup(par3);
            }
    }

    @Override
    public void shutDown() {

    }

    @Override
    public TextArea getLogArea() {
        return MES;
    }
    // End of variables declaration//GEN-END:variables
}
