/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package romanow.abc.desktop;

import romanow.abc.core.entity.contacts.Mail;
import romanow.abc.core.entity.contacts.Phone;
import romanow.abc.core.entity.users.Person;

/**
 *
 * @author romanow
 */
public class PersonPanel extends javax.swing.JFrame {
    private I_OK ok;
    private EntityPanelUni personPanel;
    /**
     * Creates new form PersonPanel
     */
    public PersonPanel(Client main, long oid, String title, I_OK ok0) {
        initComponents();
        ok = ok0;
        setTitle(title);
        setVisible(true);
        setBounds(200,200,620,220);
        personPanel = new EntityPanelUni(10,10,null,"Person",main,false,0,0){
            @Override
            public void showRecord() {
                if (current==null) return;
                Person person = (Person)current;
                N1.setText(person.getLastName());
                N2.setText(person.getFirstName());
                N3.setText(person.getMiddleName());
                POST.setText(person.getPost());
                PHONE.setText(person.getPhone().toString());
                MAIL.setText(person.getMail().toString());
                }
            @Override
            public void updateRecord() {
                if (current==null) return;
                Person person = (Person)current;
                person.setLastName(N1.getText());
                person.setFirstName(N2.getText());
                person.setMiddleName(N3.getText());
                person.setPost(POST.getText());
                person.setMail(new Mail(MAIL.getText()));
                person.setPhone(new Phone(PHONE.getText()));
                }
            };
        add(personPanel);
        personPanel.getAllEvent();
        if (oid!=0){
            personPanel.seekToId(oid);
            personPanel.getById();
            }
        }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        MAIL = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        N1 = new javax.swing.JTextField();
        N2 = new javax.swing.JTextField();
        N3 = new javax.swing.JTextField();
        POST = new javax.swing.JTextField();
        PHONE = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        MES = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(null);
        getContentPane().add(MAIL);
        MAIL.setBounds(310, 110, 110, 25);

        jLabel1.setText("E-mail");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(230, 120, 70, 14);
        getContentPane().add(N1);
        N1.setBounds(90, 50, 110, 25);
        getContentPane().add(N2);
        N2.setBounds(90, 80, 110, 25);
        getContentPane().add(N3);
        N3.setBounds(90, 110, 110, 25);
        getContentPane().add(POST);
        POST.setBounds(310, 50, 110, 25);
        getContentPane().add(PHONE);
        PHONE.setBounds(310, 80, 110, 25);

        jButton1.setText("ОК");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(10, 150, 50, 23);

        jLabel2.setText("Фамилия");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(10, 60, 70, 14);

        jLabel3.setText("Имя");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(10, 90, 70, 14);

        jLabel4.setText("Отчество");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(10, 120, 70, 14);

        jLabel5.setText("Должность");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(230, 60, 70, 14);

        jLabel6.setText("Телефон");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(230, 90, 70, 14);
        getContentPane().add(MES);
        MES.setBounds(90, 150, 330, 25);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        personPanel.updateRecord();
        Person person = (Person)personPanel.current;
        if (person==null){
            ok.onOK(null);
            dispose();
            return;
            }
        boolean invalid = !person.getPhone().valid();
        boolean invalid2 = !person.getMail().valid();
        if (invalid2 && person.getMail().toString().length()!=0){
            MES.setText("E-mail ???");
            return;
            }
        if (invalid) {
            MES.setText("Номер телефона ???");
            return;
            }
        if (personPanel.isNewRecord()){
            MES.setText("Сохраните изменения");
            return;
            }
        ok.onOK(person);
        dispose();
    }//GEN-LAST:event_jButton1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField MAIL;
    private javax.swing.JTextField MES;
    private javax.swing.JTextField N1;
    private javax.swing.JTextField N2;
    private javax.swing.JTextField N3;
    private javax.swing.JTextField PHONE;
    private javax.swing.JTextField POST;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    // End of variables declaration//GEN-END:variables
}
