/*
 * OpenAPI definition
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package romanow.abc.exam.model;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
import romanow.abc.exam.model.AccountBean;

/**
 * CreateTeacherBean
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.java.JavaClientCodegen", date = "2022-04-20T22:54:15.839+07:00[Asia/Novosibirsk]")
public class CreateTeacherBean {

  @SerializedName("account")
  private AccountBean account = null;
  
  @SerializedName("disciplineIds")
  private List<Long> disciplineIds = null;
  
  public CreateTeacherBean account(AccountBean account) {
    this.account = account;
    return this;
  }

  
  /**
  * Get account
  * @return account
  **/
  @ApiModelProperty(value = "")
  public AccountBean getAccount() {
    return account;
  }
  public void setAccount(AccountBean account) {
    this.account = account;
  }
  
  public CreateTeacherBean disciplineIds(List<Long> disciplineIds) {
    this.disciplineIds = disciplineIds;
    return this;
  }

  public CreateTeacherBean addDisciplineIdsItem(Long disciplineIdsItem) {
    
    if (this.disciplineIds == null) {
      this.disciplineIds = new ArrayList<Long>();
    }
    
    this.disciplineIds.add(disciplineIdsItem);
    return this;
  }
  
  /**
  * Get disciplineIds
  * @return disciplineIds
  **/
  @ApiModelProperty(value = "")
  public List<Long> getDisciplineIds() {
    return disciplineIds;
  }
  public void setDisciplineIds(List<Long> disciplineIds) {
    this.disciplineIds = disciplineIds;
  }
  
  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    CreateTeacherBean createTeacherBean = (CreateTeacherBean) o;
    return Objects.equals(this.account, createTeacherBean.account) &&
        Objects.equals(this.disciplineIds, createTeacherBean.disciplineIds);
  }

  @Override
  public int hashCode() {
    return java.util.Objects.hash(account, disciplineIds);
  }
  
  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class CreateTeacherBean {\n");
    
    sb.append("    account: ").append(toIndentedString(account)).append("\n");
    sb.append("    disciplineIds: ").append(toIndentedString(disciplineIds)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

  
}



