/*
 * OpenAPI definition
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package romanow.abc.exam.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.v3.oas.annotations.media.Schema;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
/**
 * CreateRatingSystemBean
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2022-04-22T14:47:34.663+07:00[Asia/Novosibirsk]")
public class CreateRatingSystemBean {
  @SerializedName("name")
  private String name = null;

  @SerializedName("approvedRatingsForQuestion")
  private List<Integer> approvedRatingsForQuestion = null;

  @SerializedName("rejectedRatingsForQuestion")
  private List<Integer> rejectedRatingsForQuestion = null;

  @SerializedName("approvedRatingsForExercise")
  private List<Integer> approvedRatingsForExercise = null;

  @SerializedName("rejectedRatingsForExercise")
  private List<Integer> rejectedRatingsForExercise = null;

  public CreateRatingSystemBean name(String name) {
    this.name = name;
    return this;
  }

   /**
   * Get name
   * @return name
  **/
  @Schema(description = "")
  public String getName() {
    return name;
  }

  public void setName(String name) {
    this.name = name;
  }

  public CreateRatingSystemBean approvedRatingsForQuestion(List<Integer> approvedRatingsForQuestion) {
    this.approvedRatingsForQuestion = approvedRatingsForQuestion;
    return this;
  }

  public CreateRatingSystemBean addApprovedRatingsForQuestionItem(Integer approvedRatingsForQuestionItem) {
    if (this.approvedRatingsForQuestion == null) {
      this.approvedRatingsForQuestion = new ArrayList<Integer>();
    }
    this.approvedRatingsForQuestion.add(approvedRatingsForQuestionItem);
    return this;
  }

   /**
   * Get approvedRatingsForQuestion
   * @return approvedRatingsForQuestion
  **/
  @Schema(description = "")
  public List<Integer> getApprovedRatingsForQuestion() {
    return approvedRatingsForQuestion;
  }

  public void setApprovedRatingsForQuestion(List<Integer> approvedRatingsForQuestion) {
    this.approvedRatingsForQuestion = approvedRatingsForQuestion;
  }

  public CreateRatingSystemBean rejectedRatingsForQuestion(List<Integer> rejectedRatingsForQuestion) {
    this.rejectedRatingsForQuestion = rejectedRatingsForQuestion;
    return this;
  }

  public CreateRatingSystemBean addRejectedRatingsForQuestionItem(Integer rejectedRatingsForQuestionItem) {
    if (this.rejectedRatingsForQuestion == null) {
      this.rejectedRatingsForQuestion = new ArrayList<Integer>();
    }
    this.rejectedRatingsForQuestion.add(rejectedRatingsForQuestionItem);
    return this;
  }

   /**
   * Get rejectedRatingsForQuestion
   * @return rejectedRatingsForQuestion
  **/
  @Schema(description = "")
  public List<Integer> getRejectedRatingsForQuestion() {
    return rejectedRatingsForQuestion;
  }

  public void setRejectedRatingsForQuestion(List<Integer> rejectedRatingsForQuestion) {
    this.rejectedRatingsForQuestion = rejectedRatingsForQuestion;
  }

  public CreateRatingSystemBean approvedRatingsForExercise(List<Integer> approvedRatingsForExercise) {
    this.approvedRatingsForExercise = approvedRatingsForExercise;
    return this;
  }

  public CreateRatingSystemBean addApprovedRatingsForExerciseItem(Integer approvedRatingsForExerciseItem) {
    if (this.approvedRatingsForExercise == null) {
      this.approvedRatingsForExercise = new ArrayList<Integer>();
    }
    this.approvedRatingsForExercise.add(approvedRatingsForExerciseItem);
    return this;
  }

   /**
   * Get approvedRatingsForExercise
   * @return approvedRatingsForExercise
  **/
  @Schema(description = "")
  public List<Integer> getApprovedRatingsForExercise() {
    return approvedRatingsForExercise;
  }

  public void setApprovedRatingsForExercise(List<Integer> approvedRatingsForExercise) {
    this.approvedRatingsForExercise = approvedRatingsForExercise;
  }

  public CreateRatingSystemBean rejectedRatingsForExercise(List<Integer> rejectedRatingsForExercise) {
    this.rejectedRatingsForExercise = rejectedRatingsForExercise;
    return this;
  }

  public CreateRatingSystemBean addRejectedRatingsForExerciseItem(Integer rejectedRatingsForExerciseItem) {
    if (this.rejectedRatingsForExercise == null) {
      this.rejectedRatingsForExercise = new ArrayList<Integer>();
    }
    this.rejectedRatingsForExercise.add(rejectedRatingsForExerciseItem);
    return this;
  }

   /**
   * Get rejectedRatingsForExercise
   * @return rejectedRatingsForExercise
  **/
  @Schema(description = "")
  public List<Integer> getRejectedRatingsForExercise() {
    return rejectedRatingsForExercise;
  }

  public void setRejectedRatingsForExercise(List<Integer> rejectedRatingsForExercise) {
    this.rejectedRatingsForExercise = rejectedRatingsForExercise;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    CreateRatingSystemBean createRatingSystemBean = (CreateRatingSystemBean) o;
    return Objects.equals(this.name, createRatingSystemBean.name) &&
        Objects.equals(this.approvedRatingsForQuestion, createRatingSystemBean.approvedRatingsForQuestion) &&
        Objects.equals(this.rejectedRatingsForQuestion, createRatingSystemBean.rejectedRatingsForQuestion) &&
        Objects.equals(this.approvedRatingsForExercise, createRatingSystemBean.approvedRatingsForExercise) &&
        Objects.equals(this.rejectedRatingsForExercise, createRatingSystemBean.rejectedRatingsForExercise);
  }

  @Override
  public int hashCode() {
    return Objects.hash(name, approvedRatingsForQuestion, rejectedRatingsForQuestion, approvedRatingsForExercise, rejectedRatingsForExercise);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class CreateRatingSystemBean {\n");
    
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("    approvedRatingsForQuestion: ").append(toIndentedString(approvedRatingsForQuestion)).append("\n");
    sb.append("    rejectedRatingsForQuestion: ").append(toIndentedString(rejectedRatingsForQuestion)).append("\n");
    sb.append("    approvedRatingsForExercise: ").append(toIndentedString(approvedRatingsForExercise)).append("\n");
    sb.append("    rejectedRatingsForExercise: ").append(toIndentedString(rejectedRatingsForExercise)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
