/*
 * OpenAPI definition
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package romanow.abc.exam.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.v3.oas.annotations.media.Schema;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
/**
 * ExamRuleBean
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2022-04-24T21:32:27.604+07:00[Asia/Novosibirsk]")
public class ExamRuleBean {
  @SerializedName("id")
  private Long id = null;

  @SerializedName("name")
  private String name = null;

  @SerializedName("themeIds")
  private List<Long> themeIds = null;

  @SerializedName("disciplineId")
  private Long disciplineId = null;

  @SerializedName("questionCount")
  private Integer questionCount = null;

  @SerializedName("exerciseCount")
  private Integer exerciseCount = null;

  @SerializedName("duration")
  private Integer duration = null;

  @SerializedName("minimalRating")
  private Integer minimalRating = null;

  @SerializedName("ratingSystemId")
  private Long ratingSystemId = null;

  public ExamRuleBean id(Long id) {
    this.id = id;
    return this;
  }

   /**
   * Get id
   * @return id
  **/
  @Schema(description = "")
  public Long getId() {
    return id;
  }

  public void setId(Long id) {
    this.id = id;
  }

  public ExamRuleBean name(String name) {
    this.name = name;
    return this;
  }

   /**
   * Get name
   * @return name
  **/
  @Schema(description = "")
  public String getName() {
    return name;
  }

  public void setName(String name) {
    this.name = name;
  }

  public ExamRuleBean themeIds(List<Long> themeIds) {
    this.themeIds = themeIds;
    return this;
  }

  public ExamRuleBean addThemeIdsItem(Long themeIdsItem) {
    if (this.themeIds == null) {
      this.themeIds = new ArrayList<Long>();
    }
    this.themeIds.add(themeIdsItem);
    return this;
  }

   /**
   * Get themeIds
   * @return themeIds
  **/
  @Schema(description = "")
  public List<Long> getThemeIds() {
    return themeIds;
  }

  public void setThemeIds(List<Long> themeIds) {
    this.themeIds = themeIds;
  }

  public ExamRuleBean disciplineId(Long disciplineId) {
    this.disciplineId = disciplineId;
    return this;
  }

   /**
   * Get disciplineId
   * @return disciplineId
  **/
  @Schema(description = "")
  public Long getDisciplineId() {
    return disciplineId;
  }

  public void setDisciplineId(Long disciplineId) {
    this.disciplineId = disciplineId;
  }

  public ExamRuleBean questionCount(Integer questionCount) {
    this.questionCount = questionCount;
    return this;
  }

   /**
   * Get questionCount
   * @return questionCount
  **/
  @Schema(description = "")
  public Integer getQuestionCount() {
    return questionCount;
  }

  public void setQuestionCount(Integer questionCount) {
    this.questionCount = questionCount;
  }

  public ExamRuleBean exerciseCount(Integer exerciseCount) {
    this.exerciseCount = exerciseCount;
    return this;
  }

   /**
   * Get exerciseCount
   * @return exerciseCount
  **/
  @Schema(description = "")
  public Integer getExerciseCount() {
    return exerciseCount;
  }

  public void setExerciseCount(Integer exerciseCount) {
    this.exerciseCount = exerciseCount;
  }

  public ExamRuleBean duration(Integer duration) {
    this.duration = duration;
    return this;
  }

   /**
   * Get duration
   * @return duration
  **/
  @Schema(description = "")
  public Integer getDuration() {
    return duration;
  }

  public void setDuration(Integer duration) {
    this.duration = duration;
  }

  public ExamRuleBean minimalRating(Integer minimalRating) {
    this.minimalRating = minimalRating;
    return this;
  }

   /**
   * Get minimalRating
   * @return minimalRating
  **/
  @Schema(description = "")
  public Integer getMinimalRating() {
    return minimalRating;
  }

  public void setMinimalRating(Integer minimalRating) {
    this.minimalRating = minimalRating;
  }

  public ExamRuleBean ratingSystemId(Long ratingSystemId) {
    this.ratingSystemId = ratingSystemId;
    return this;
  }

   /**
   * Get ratingSystemId
   * @return ratingSystemId
  **/
  @Schema(description = "")
  public Long getRatingSystemId() {
    return ratingSystemId;
  }

  public void setRatingSystemId(Long ratingSystemId) {
    this.ratingSystemId = ratingSystemId;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ExamRuleBean examRuleBean = (ExamRuleBean) o;
    return Objects.equals(this.id, examRuleBean.id) &&
        Objects.equals(this.name, examRuleBean.name) &&
        Objects.equals(this.themeIds, examRuleBean.themeIds) &&
        Objects.equals(this.disciplineId, examRuleBean.disciplineId) &&
        Objects.equals(this.questionCount, examRuleBean.questionCount) &&
        Objects.equals(this.exerciseCount, examRuleBean.exerciseCount) &&
        Objects.equals(this.duration, examRuleBean.duration) &&
        Objects.equals(this.minimalRating, examRuleBean.minimalRating) &&
        Objects.equals(this.ratingSystemId, examRuleBean.ratingSystemId);
  }

  @Override
  public int hashCode() {
    return Objects.hash(id, name, themeIds, disciplineId, questionCount, exerciseCount, duration, minimalRating, ratingSystemId);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ExamRuleBean {\n");
    
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("    themeIds: ").append(toIndentedString(themeIds)).append("\n");
    sb.append("    disciplineId: ").append(toIndentedString(disciplineId)).append("\n");
    sb.append("    questionCount: ").append(toIndentedString(questionCount)).append("\n");
    sb.append("    exerciseCount: ").append(toIndentedString(exerciseCount)).append("\n");
    sb.append("    duration: ").append(toIndentedString(duration)).append("\n");
    sb.append("    minimalRating: ").append(toIndentedString(minimalRating)).append("\n");
    sb.append("    ratingSystemId: ").append(toIndentedString(ratingSystemId)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
