/*
 * OpenAPI definition
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package romanow.abc.exam.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.v3.oas.annotations.media.Schema;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
import romanow.abc.exam.model.ExamBean;
import romanow.abc.exam.model.FullExamPeriodBean;
import romanow.abc.exam.model.FullExamRuleBean;
/**
 * FullExamBean
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2022-05-08T18:16:36.953+07:00[Asia/Novosibirsk]")
public class FullExamBean {
  @SerializedName("exam")
  private ExamBean exam = null;

  @SerializedName("examRule")
  private FullExamRuleBean examRule = null;

  @SerializedName("periods")
  private List<FullExamPeriodBean> periods = null;

  public FullExamBean exam(ExamBean exam) {
    this.exam = exam;
    return this;
  }

   /**
   * Get exam
   * @return exam
  **/
  @Schema(description = "")
  public ExamBean getExam() {
    return exam;
  }

  public void setExam(ExamBean exam) {
    this.exam = exam;
  }

  public FullExamBean examRule(FullExamRuleBean examRule) {
    this.examRule = examRule;
    return this;
  }

   /**
   * Get examRule
   * @return examRule
  **/
  @Schema(description = "")
  public FullExamRuleBean getExamRule() {
    return examRule;
  }

  public void setExamRule(FullExamRuleBean examRule) {
    this.examRule = examRule;
  }

  public FullExamBean periods(List<FullExamPeriodBean> periods) {
    this.periods = periods;
    return this;
  }

  public FullExamBean addPeriodsItem(FullExamPeriodBean periodsItem) {
    if (this.periods == null) {
      this.periods = new ArrayList<FullExamPeriodBean>();
    }
    this.periods.add(periodsItem);
    return this;
  }

   /**
   * Get periods
   * @return periods
  **/
  @Schema(description = "")
  public List<FullExamPeriodBean> getPeriods() {
    return periods;
  }

  public void setPeriods(List<FullExamPeriodBean> periods) {
    this.periods = periods;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    FullExamBean fullExamBean = (FullExamBean) o;
    return Objects.equals(this.exam, fullExamBean.exam) &&
        Objects.equals(this.examRule, fullExamBean.examRule) &&
        Objects.equals(this.periods, fullExamBean.periods);
  }

  @Override
  public int hashCode() {
    return Objects.hash(exam, examRule, periods);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class FullExamBean {\n");
    
    sb.append("    exam: ").append(toIndentedString(exam)).append("\n");
    sb.append("    examRule: ").append(toIndentedString(examRule)).append("\n");
    sb.append("    periods: ").append(toIndentedString(periods)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
