/*
 * OpenAPI definition
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package romanow.abc.exam.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.v3.oas.annotations.media.Schema;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
import romanow.abc.exam.model.ExamPeriodBean;
import romanow.abc.exam.model.FullTicketBean;
/**
 * FullExamPeriodBean
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2022-05-08T18:16:36.953+07:00[Asia/Novosibirsk]")
public class FullExamPeriodBean {
  @SerializedName("examPeriod")
  private ExamPeriodBean examPeriod = null;

  @SerializedName("tickets")
  private List<FullTicketBean> tickets = null;

  public FullExamPeriodBean examPeriod(ExamPeriodBean examPeriod) {
    this.examPeriod = examPeriod;
    return this;
  }

   /**
   * Get examPeriod
   * @return examPeriod
  **/
  @Schema(description = "")
  public ExamPeriodBean getExamPeriod() {
    return examPeriod;
  }

  public void setExamPeriod(ExamPeriodBean examPeriod) {
    this.examPeriod = examPeriod;
  }

  public FullExamPeriodBean tickets(List<FullTicketBean> tickets) {
    this.tickets = tickets;
    return this;
  }

  public FullExamPeriodBean addTicketsItem(FullTicketBean ticketsItem) {
    if (this.tickets == null) {
      this.tickets = new ArrayList<FullTicketBean>();
    }
    this.tickets.add(ticketsItem);
    return this;
  }

   /**
   * Get tickets
   * @return tickets
  **/
  @Schema(description = "")
  public List<FullTicketBean> getTickets() {
    return tickets;
  }

  public void setTickets(List<FullTicketBean> tickets) {
    this.tickets = tickets;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    FullExamPeriodBean fullExamPeriodBean = (FullExamPeriodBean) o;
    return Objects.equals(this.examPeriod, fullExamPeriodBean.examPeriod) &&
        Objects.equals(this.tickets, fullExamPeriodBean.tickets);
  }

  @Override
  public int hashCode() {
    return Objects.hash(examPeriod, tickets);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class FullExamPeriodBean {\n");
    
    sb.append("    examPeriod: ").append(toIndentedString(examPeriod)).append("\n");
    sb.append("    tickets: ").append(toIndentedString(tickets)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
