/*
 * OpenAPI definition
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package romanow.abc.exam.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.v3.oas.annotations.media.Schema;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
import romanow.abc.exam.model.DisciplineBean;
import romanow.abc.exam.model.GroupBean;
import romanow.abc.exam.model.StudentBean;
/**
 * FullGroupBean
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2022-04-24T21:32:27.604+07:00[Asia/Novosibirsk]")
public class FullGroupBean {
  @SerializedName("group")
  private GroupBean group = null;

  @SerializedName("students")
  private List<StudentBean> students = null;

  @SerializedName("disciplines")
  private List<DisciplineBean> disciplines = null;

  public FullGroupBean group(GroupBean group) {
    this.group = group;
    return this;
  }

   /**
   * Get group
   * @return group
  **/
  @Schema(description = "")
  public GroupBean getGroup() {
    return group;
  }

  public void setGroup(GroupBean group) {
    this.group = group;
  }

  public FullGroupBean students(List<StudentBean> students) {
    this.students = students;
    return this;
  }

  public FullGroupBean addStudentsItem(StudentBean studentsItem) {
    if (this.students == null) {
      this.students = new ArrayList<StudentBean>();
    }
    this.students.add(studentsItem);
    return this;
  }

   /**
   * Get students
   * @return students
  **/
  @Schema(description = "")
  public List<StudentBean> getStudents() {
    return students;
  }

  public void setStudents(List<StudentBean> students) {
    this.students = students;
  }

  public FullGroupBean disciplines(List<DisciplineBean> disciplines) {
    this.disciplines = disciplines;
    return this;
  }

  public FullGroupBean addDisciplinesItem(DisciplineBean disciplinesItem) {
    if (this.disciplines == null) {
      this.disciplines = new ArrayList<DisciplineBean>();
    }
    this.disciplines.add(disciplinesItem);
    return this;
  }

   /**
   * Get disciplines
   * @return disciplines
  **/
  @Schema(description = "")
  public List<DisciplineBean> getDisciplines() {
    return disciplines;
  }

  public void setDisciplines(List<DisciplineBean> disciplines) {
    this.disciplines = disciplines;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    FullGroupBean fullGroupBean = (FullGroupBean) o;
    return Objects.equals(this.group, fullGroupBean.group) &&
        Objects.equals(this.students, fullGroupBean.students) &&
        Objects.equals(this.disciplines, fullGroupBean.disciplines);
  }

  @Override
  public int hashCode() {
    return Objects.hash(group, students, disciplines);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class FullGroupBean {\n");
    
    sb.append("    group: ").append(toIndentedString(group)).append("\n");
    sb.append("    students: ").append(toIndentedString(students)).append("\n");
    sb.append("    disciplines: ").append(toIndentedString(disciplines)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
