/*
 * OpenAPI definition
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package romanow.abc.exam.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.v3.oas.annotations.media.Schema;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
import romanow.abc.exam.model.FullAnswerBean;
import romanow.abc.exam.model.FullExamBean;
import romanow.abc.exam.model.FullGroupRatingBean;
import romanow.abc.exam.model.FullStudentBean;
import romanow.abc.exam.model.StudentRatingBean;
/**
 * FullStudentRatingBean
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2022-06-01T14:56:15.142+07:00[Asia/Novosibirsk]")
public class FullStudentRatingBean {
  @SerializedName("studentRating")
  private StudentRatingBean studentRating = null;

  @SerializedName("answers")
  private List<FullAnswerBean> answers = null;

  @SerializedName("student")
  private FullStudentBean student = null;

  @SerializedName("exam")
  private FullExamBean exam = null;

  @SerializedName("groupRating")
  private FullGroupRatingBean groupRating = null;

  public FullStudentRatingBean studentRating(StudentRatingBean studentRating) {
    this.studentRating = studentRating;
    return this;
  }

   /**
   * Get studentRating
   * @return studentRating
  **/
  @Schema(description = "")
  public StudentRatingBean getStudentRating() {
    return studentRating;
  }

  public void setStudentRating(StudentRatingBean studentRating) {
    this.studentRating = studentRating;
  }

  public FullStudentRatingBean answers(List<FullAnswerBean> answers) {
    this.answers = answers;
    return this;
  }

  public FullStudentRatingBean addAnswersItem(FullAnswerBean answersItem) {
    if (this.answers == null) {
      this.answers = new ArrayList<FullAnswerBean>();
    }
    this.answers.add(answersItem);
    return this;
  }

   /**
   * Get answers
   * @return answers
  **/
  @Schema(description = "")
  public List<FullAnswerBean> getAnswers() {
    return answers;
  }

  public void setAnswers(List<FullAnswerBean> answers) {
    this.answers = answers;
  }

  public FullStudentRatingBean student(FullStudentBean student) {
    this.student = student;
    return this;
  }

   /**
   * Get student
   * @return student
  **/
  @Schema(description = "")
  public FullStudentBean getStudent() {
    return student;
  }

  public void setStudent(FullStudentBean student) {
    this.student = student;
  }

  public FullStudentRatingBean exam(FullExamBean exam) {
    this.exam = exam;
    return this;
  }

   /**
   * Get exam
   * @return exam
  **/
  @Schema(description = "")
  public FullExamBean getExam() {
    return exam;
  }

  public void setExam(FullExamBean exam) {
    this.exam = exam;
  }

  public FullStudentRatingBean groupRating(FullGroupRatingBean groupRating) {
    this.groupRating = groupRating;
    return this;
  }

   /**
   * Get groupRating
   * @return groupRating
  **/
  @Schema(description = "")
  public FullGroupRatingBean getGroupRating() {
    return groupRating;
  }

  public void setGroupRating(FullGroupRatingBean groupRating) {
    this.groupRating = groupRating;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    FullStudentRatingBean fullStudentRatingBean = (FullStudentRatingBean) o;
    return Objects.equals(this.studentRating, fullStudentRatingBean.studentRating) &&
        Objects.equals(this.answers, fullStudentRatingBean.answers) &&
        Objects.equals(this.student, fullStudentRatingBean.student) &&
        Objects.equals(this.exam, fullStudentRatingBean.exam) &&
        Objects.equals(this.groupRating, fullStudentRatingBean.groupRating);
  }

  @Override
  public int hashCode() {
    return Objects.hash(studentRating, answers, student, exam, groupRating);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class FullStudentRatingBean {\n");
    
    sb.append("    studentRating: ").append(toIndentedString(studentRating)).append("\n");
    sb.append("    answers: ").append(toIndentedString(answers)).append("\n");
    sb.append("    student: ").append(toIndentedString(student)).append("\n");
    sb.append("    exam: ").append(toIndentedString(exam)).append("\n");
    sb.append("    groupRating: ").append(toIndentedString(groupRating)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
