/*
 * OpenAPI definition
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package romanow.abc.exam.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.v3.oas.annotations.media.Schema;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
import romanow.abc.exam.model.FullDisciplineBean;
import romanow.abc.exam.model.FullGroupBean;
import romanow.abc.exam.model.FullStudentRatingBean;
import romanow.abc.exam.model.GroupRatingBean;
/**
 * FullGroupRatingBean
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2022-06-01T14:56:15.142+07:00[Asia/Novosibirsk]")
public class FullGroupRatingBean {
  @SerializedName("groupRating")
  private GroupRatingBean groupRating = null;

  @SerializedName("studentRatings")
  private List<FullStudentRatingBean> studentRatings = null;

  @SerializedName("discipline")
  private FullDisciplineBean discipline = null;

  @SerializedName("group")
  private FullGroupBean group = null;

  public FullGroupRatingBean groupRating(GroupRatingBean groupRating) {
    this.groupRating = groupRating;
    return this;
  }

   /**
   * Get groupRating
   * @return groupRating
  **/
  @Schema(description = "")
  public GroupRatingBean getGroupRating() {
    return groupRating;
  }

  public void setGroupRating(GroupRatingBean groupRating) {
    this.groupRating = groupRating;
  }

  public FullGroupRatingBean studentRatings(List<FullStudentRatingBean> studentRatings) {
    this.studentRatings = studentRatings;
    return this;
  }

  public FullGroupRatingBean addStudentRatingsItem(FullStudentRatingBean studentRatingsItem) {
    if (this.studentRatings == null) {
      this.studentRatings = new ArrayList<FullStudentRatingBean>();
    }
    this.studentRatings.add(studentRatingsItem);
    return this;
  }

   /**
   * Get studentRatings
   * @return studentRatings
  **/
  @Schema(description = "")
  public List<FullStudentRatingBean> getStudentRatings() {
    return studentRatings;
  }

  public void setStudentRatings(List<FullStudentRatingBean> studentRatings) {
    this.studentRatings = studentRatings;
  }

  public FullGroupRatingBean discipline(FullDisciplineBean discipline) {
    this.discipline = discipline;
    return this;
  }

   /**
   * Get discipline
   * @return discipline
  **/
  @Schema(description = "")
  public FullDisciplineBean getDiscipline() {
    return discipline;
  }

  public void setDiscipline(FullDisciplineBean discipline) {
    this.discipline = discipline;
  }

  public FullGroupRatingBean group(FullGroupBean group) {
    this.group = group;
    return this;
  }

   /**
   * Get group
   * @return group
  **/
  @Schema(description = "")
  public FullGroupBean getGroup() {
    return group;
  }

  public void setGroup(FullGroupBean group) {
    this.group = group;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    FullGroupRatingBean fullGroupRatingBean = (FullGroupRatingBean) o;
    return Objects.equals(this.groupRating, fullGroupRatingBean.groupRating) &&
        Objects.equals(this.studentRatings, fullGroupRatingBean.studentRatings) &&
        Objects.equals(this.discipline, fullGroupRatingBean.discipline) &&
        Objects.equals(this.group, fullGroupRatingBean.group);
  }

  @Override
  public int hashCode() {
    return Objects.hash(groupRating, studentRatings, discipline, group);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class FullGroupRatingBean {\n");
    
    sb.append("    groupRating: ").append(toIndentedString(groupRating)).append("\n");
    sb.append("    studentRatings: ").append(toIndentedString(studentRatings)).append("\n");
    sb.append("    discipline: ").append(toIndentedString(discipline)).append("\n");
    sb.append("    group: ").append(toIndentedString(group)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
