/*
 * OpenAPI definition
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package romanow.abc.exam.model;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import romanow.abc.exam.model.ExamPeriodBean;
import romanow.abc.exam.model.TeacherBean;

/**
 * StudentTicketBean
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.java.JavaClientCodegen", date = "2022-04-22T11:27:57.635+07:00[Asia/Novosibirsk]")
public class StudentTicketBean {

  @SerializedName("id")
  private Long id = null;
  
  @SerializedName("disciplineName")
  private String disciplineName = null;
  
  @SerializedName("semesterRating")
  private Integer semesterRating = null;
  
  @SerializedName("examRating")
  private Integer examRating = null;
  
  @SerializedName("allowed")
  private Boolean allowed = null;
  
  @SerializedName("examPeriod")
  private ExamPeriodBean examPeriod = null;
  
  @SerializedName("teacher")
  private TeacherBean teacher = null;
  
  @SerializedName("maxQuestionRating")
  private Integer maxQuestionRating = null;
  
  @SerializedName("maxExerciseRating")
  private Integer maxExerciseRating = null;
  
  public StudentTicketBean id(Long id) {
    this.id = id;
    return this;
  }

  
  /**
  * Get id
  * @return id
  **/
  @ApiModelProperty(value = "")
  public Long getId() {
    return id;
  }
  public void setId(Long id) {
    this.id = id;
  }
  
  public StudentTicketBean disciplineName(String disciplineName) {
    this.disciplineName = disciplineName;
    return this;
  }

  
  /**
  * Get disciplineName
  * @return disciplineName
  **/
  @ApiModelProperty(value = "")
  public String getDisciplineName() {
    return disciplineName;
  }
  public void setDisciplineName(String disciplineName) {
    this.disciplineName = disciplineName;
  }
  
  public StudentTicketBean semesterRating(Integer semesterRating) {
    this.semesterRating = semesterRating;
    return this;
  }

  
  /**
  * Get semesterRating
  * @return semesterRating
  **/
  @ApiModelProperty(value = "")
  public Integer getSemesterRating() {
    return semesterRating;
  }
  public void setSemesterRating(Integer semesterRating) {
    this.semesterRating = semesterRating;
  }
  
  public StudentTicketBean examRating(Integer examRating) {
    this.examRating = examRating;
    return this;
  }

  
  /**
  * Get examRating
  * @return examRating
  **/
  @ApiModelProperty(value = "")
  public Integer getExamRating() {
    return examRating;
  }
  public void setExamRating(Integer examRating) {
    this.examRating = examRating;
  }
  
  public StudentTicketBean allowed(Boolean allowed) {
    this.allowed = allowed;
    return this;
  }

  
  /**
  * Get allowed
  * @return allowed
  **/
  @ApiModelProperty(value = "")
  public Boolean isAllowed() {
    return allowed;
  }
  public void setAllowed(Boolean allowed) {
    this.allowed = allowed;
  }
  
  public StudentTicketBean examPeriod(ExamPeriodBean examPeriod) {
    this.examPeriod = examPeriod;
    return this;
  }

  
  /**
  * Get examPeriod
  * @return examPeriod
  **/
  @ApiModelProperty(value = "")
  public ExamPeriodBean getExamPeriod() {
    return examPeriod;
  }
  public void setExamPeriod(ExamPeriodBean examPeriod) {
    this.examPeriod = examPeriod;
  }
  
  public StudentTicketBean teacher(TeacherBean teacher) {
    this.teacher = teacher;
    return this;
  }

  
  /**
  * Get teacher
  * @return teacher
  **/
  @ApiModelProperty(value = "")
  public TeacherBean getTeacher() {
    return teacher;
  }
  public void setTeacher(TeacherBean teacher) {
    this.teacher = teacher;
  }
  
  public StudentTicketBean maxQuestionRating(Integer maxQuestionRating) {
    this.maxQuestionRating = maxQuestionRating;
    return this;
  }

  
  /**
  * Get maxQuestionRating
  * @return maxQuestionRating
  **/
  @ApiModelProperty(value = "")
  public Integer getMaxQuestionRating() {
    return maxQuestionRating;
  }
  public void setMaxQuestionRating(Integer maxQuestionRating) {
    this.maxQuestionRating = maxQuestionRating;
  }
  
  public StudentTicketBean maxExerciseRating(Integer maxExerciseRating) {
    this.maxExerciseRating = maxExerciseRating;
    return this;
  }

  
  /**
  * Get maxExerciseRating
  * @return maxExerciseRating
  **/
  @ApiModelProperty(value = "")
  public Integer getMaxExerciseRating() {
    return maxExerciseRating;
  }
  public void setMaxExerciseRating(Integer maxExerciseRating) {
    this.maxExerciseRating = maxExerciseRating;
  }
  
  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    StudentTicketBean studentTicketBean = (StudentTicketBean) o;
    return Objects.equals(this.id, studentTicketBean.id) &&
        Objects.equals(this.disciplineName, studentTicketBean.disciplineName) &&
        Objects.equals(this.semesterRating, studentTicketBean.semesterRating) &&
        Objects.equals(this.examRating, studentTicketBean.examRating) &&
        Objects.equals(this.allowed, studentTicketBean.allowed) &&
        Objects.equals(this.examPeriod, studentTicketBean.examPeriod) &&
        Objects.equals(this.teacher, studentTicketBean.teacher) &&
        Objects.equals(this.maxQuestionRating, studentTicketBean.maxQuestionRating) &&
        Objects.equals(this.maxExerciseRating, studentTicketBean.maxExerciseRating);
  }

  @Override
  public int hashCode() {
    return java.util.Objects.hash(id, disciplineName, semesterRating, examRating, allowed, examPeriod, teacher, maxQuestionRating, maxExerciseRating);
  }
  
  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class StudentTicketBean {\n");
    
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    disciplineName: ").append(toIndentedString(disciplineName)).append("\n");
    sb.append("    semesterRating: ").append(toIndentedString(semesterRating)).append("\n");
    sb.append("    examRating: ").append(toIndentedString(examRating)).append("\n");
    sb.append("    allowed: ").append(toIndentedString(allowed)).append("\n");
    sb.append("    examPeriod: ").append(toIndentedString(examPeriod)).append("\n");
    sb.append("    teacher: ").append(toIndentedString(teacher)).append("\n");
    sb.append("    maxQuestionRating: ").append(toIndentedString(maxQuestionRating)).append("\n");
    sb.append("    maxExerciseRating: ").append(toIndentedString(maxExerciseRating)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

  
}



