/*
 * OpenAPI definition
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package romanow.abc.exam.model;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import romanow.abc.exam.model.StudentTaskBean;

/**
 * StudentAnswerBean
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.java.JavaClientCodegen", date = "2022-04-22T11:27:57.635+07:00[Asia/Novosibirsk]")
public class StudentAnswerBean {

  @SerializedName("id")
  private Long id = null;
  
  @SerializedName("task")
  private StudentTaskBean task = null;
  
  @SerializedName("rating")
  private Integer rating = null;
  
  @SerializedName("ticketId")
  private Long ticketId = null;
  
  /**
   * Gets or Sets status
   */
  @JsonAdapter(StatusEnum.Adapter.class)
  public enum StatusEnum {
    
    CHECKING("CHECKING"),
    REVISION("REVISION"),
    REJECTED("REJECTED"),
    APPROVED("APPROVED");

    private String value;

    StatusEnum(String value) {
      this.value = value;
    }
    
    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }
    
    public static StatusEnum fromValue(String text) {
      for (StatusEnum b : StatusEnum.values()) {
        if (String.valueOf(b.value).equals(text)) {
          return b;
        }
      }
      return null;
    }
    
    public static class Adapter extends TypeAdapter<StatusEnum> {
      @Override
      public void write(final JsonWriter jsonWriter, final StatusEnum enumeration) throws IOException {
        jsonWriter.value(enumeration.getValue());
      }

      @Override
      public StatusEnum read(final JsonReader jsonReader) throws IOException {
        String value = jsonReader.nextString();
        return StatusEnum.fromValue(String.valueOf(value));
      }
    }
  }
  
  @SerializedName("status")
  private StatusEnum status = null;
  
  @SerializedName("number")
  private Integer number = null;
  
  public StudentAnswerBean id(Long id) {
    this.id = id;
    return this;
  }

  
  /**
  * Get id
  * @return id
  **/
  @ApiModelProperty(value = "")
  public Long getId() {
    return id;
  }
  public void setId(Long id) {
    this.id = id;
  }
  
  public StudentAnswerBean task(StudentTaskBean task) {
    this.task = task;
    return this;
  }

  
  /**
  * Get task
  * @return task
  **/
  @ApiModelProperty(value = "")
  public StudentTaskBean getTask() {
    return task;
  }
  public void setTask(StudentTaskBean task) {
    this.task = task;
  }
  
  public StudentAnswerBean rating(Integer rating) {
    this.rating = rating;
    return this;
  }

  
  /**
  * Get rating
  * @return rating
  **/
  @ApiModelProperty(value = "")
  public Integer getRating() {
    return rating;
  }
  public void setRating(Integer rating) {
    this.rating = rating;
  }
  
  public StudentAnswerBean ticketId(Long ticketId) {
    this.ticketId = ticketId;
    return this;
  }

  
  /**
  * Get ticketId
  * @return ticketId
  **/
  @ApiModelProperty(value = "")
  public Long getTicketId() {
    return ticketId;
  }
  public void setTicketId(Long ticketId) {
    this.ticketId = ticketId;
  }
  
  public StudentAnswerBean status(StatusEnum status) {
    this.status = status;
    return this;
  }

  
  /**
  * Get status
  * @return status
  **/
  @ApiModelProperty(value = "")
  public StatusEnum getStatus() {
    return status;
  }
  public void setStatus(StatusEnum status) {
    this.status = status;
  }
  
  public StudentAnswerBean number(Integer number) {
    this.number = number;
    return this;
  }

  
  /**
  * Get number
  * @return number
  **/
  @ApiModelProperty(value = "")
  public Integer getNumber() {
    return number;
  }
  public void setNumber(Integer number) {
    this.number = number;
  }
  
  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    StudentAnswerBean studentAnswerBean = (StudentAnswerBean) o;
    return Objects.equals(this.id, studentAnswerBean.id) &&
        Objects.equals(this.task, studentAnswerBean.task) &&
        Objects.equals(this.rating, studentAnswerBean.rating) &&
        Objects.equals(this.ticketId, studentAnswerBean.ticketId) &&
        Objects.equals(this.status, studentAnswerBean.status) &&
        Objects.equals(this.number, studentAnswerBean.number);
  }

  @Override
  public int hashCode() {
    return java.util.Objects.hash(id, task, rating, ticketId, status, number);
  }
  
  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class StudentAnswerBean {\n");
    
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    task: ").append(toIndentedString(task)).append("\n");
    sb.append("    rating: ").append(toIndentedString(rating)).append("\n");
    sb.append("    ticketId: ").append(toIndentedString(ticketId)).append("\n");
    sb.append("    status: ").append(toIndentedString(status)).append("\n");
    sb.append("    number: ").append(toIndentedString(number)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

  
}



