/*
 * OpenAPI definition
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package romanow.abc.exam.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.v3.oas.annotations.media.Schema;
import java.io.IOException;
/**
 * TicketBean
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2022-05-08T18:16:36.953+07:00[Asia/Novosibirsk]")
public class TicketBean {
  @SerializedName("id")
  private Long id = null;

  @SerializedName("semesterRating")
  private Integer semesterRating = null;

  @SerializedName("examRating")
  private Integer examRating = null;

  @SerializedName("allowed")
  private Boolean allowed = null;

  @SerializedName("examPeriodId")
  private Long examPeriodId = null;

  @SerializedName("studentId")
  private Long studentId = null;

  public TicketBean id(Long id) {
    this.id = id;
    return this;
  }

   /**
   * Get id
   * @return id
  **/
  @Schema(description = "")
  public Long getId() {
    return id;
  }

  public void setId(Long id) {
    this.id = id;
  }

  public TicketBean semesterRating(Integer semesterRating) {
    this.semesterRating = semesterRating;
    return this;
  }

   /**
   * Get semesterRating
   * @return semesterRating
  **/
  @Schema(description = "")
  public Integer getSemesterRating() {
    return semesterRating;
  }

  public void setSemesterRating(Integer semesterRating) {
    this.semesterRating = semesterRating;
  }

  public TicketBean examRating(Integer examRating) {
    this.examRating = examRating;
    return this;
  }

   /**
   * Get examRating
   * @return examRating
  **/
  @Schema(description = "")
  public Integer getExamRating() {
    return examRating;
  }

  public void setExamRating(Integer examRating) {
    this.examRating = examRating;
  }

  public TicketBean allowed(Boolean allowed) {
    this.allowed = allowed;
    return this;
  }

   /**
   * Get allowed
   * @return allowed
  **/
  @Schema(description = "")
  public Boolean isAllowed() {
    return allowed;
  }

  public void setAllowed(Boolean allowed) {
    this.allowed = allowed;
  }

  public TicketBean examPeriodId(Long examPeriodId) {
    this.examPeriodId = examPeriodId;
    return this;
  }

   /**
   * Get examPeriodId
   * @return examPeriodId
  **/
  @Schema(description = "")
  public Long getExamPeriodId() {
    return examPeriodId;
  }

  public void setExamPeriodId(Long examPeriodId) {
    this.examPeriodId = examPeriodId;
  }

  public TicketBean studentId(Long studentId) {
    this.studentId = studentId;
    return this;
  }

   /**
   * Get studentId
   * @return studentId
  **/
  @Schema(description = "")
  public Long getStudentId() {
    return studentId;
  }

  public void setStudentId(Long studentId) {
    this.studentId = studentId;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    TicketBean ticketBean = (TicketBean) o;
    return Objects.equals(this.id, ticketBean.id) &&
        Objects.equals(this.semesterRating, ticketBean.semesterRating) &&
        Objects.equals(this.examRating, ticketBean.examRating) &&
        Objects.equals(this.allowed, ticketBean.allowed) &&
        Objects.equals(this.examPeriodId, ticketBean.examPeriodId) &&
        Objects.equals(this.studentId, ticketBean.studentId);
  }

  @Override
  public int hashCode() {
    return Objects.hash(id, semesterRating, examRating, allowed, examPeriodId, studentId);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class TicketBean {\n");
    
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    semesterRating: ").append(toIndentedString(semesterRating)).append("\n");
    sb.append("    examRating: ").append(toIndentedString(examRating)).append("\n");
    sb.append("    allowed: ").append(toIndentedString(allowed)).append("\n");
    sb.append("    examPeriodId: ").append(toIndentedString(examPeriodId)).append("\n");
    sb.append("    studentId: ").append(toIndentedString(studentId)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
