/*
 * OpenAPI definition
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package romanow.abc.exam.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.v3.oas.annotations.media.Schema;
import java.io.IOException;
/**
 * UpdateTicketBean
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2022-04-22T14:47:34.663+07:00[Asia/Novosibirsk]")
public class UpdateTicketBean {
  @SerializedName("id")
  private Long id = null;

  @SerializedName("semesterRating")
  private Integer semesterRating = null;

  @SerializedName("examRating")
  private Integer examRating = null;

  @SerializedName("allowed")
  private Boolean allowed = null;

  public UpdateTicketBean id(Long id) {
    this.id = id;
    return this;
  }

   /**
   * Get id
   * @return id
  **/
  @Schema(required = true, description = "")
  public Long getId() {
    return id;
  }

  public void setId(Long id) {
    this.id = id;
  }

  public UpdateTicketBean semesterRating(Integer semesterRating) {
    this.semesterRating = semesterRating;
    return this;
  }

   /**
   * Get semesterRating
   * @return semesterRating
  **/
  @Schema(required = true, description = "")
  public Integer getSemesterRating() {
    return semesterRating;
  }

  public void setSemesterRating(Integer semesterRating) {
    this.semesterRating = semesterRating;
  }

  public UpdateTicketBean examRating(Integer examRating) {
    this.examRating = examRating;
    return this;
  }

   /**
   * Get examRating
   * @return examRating
  **/
  @Schema(required = true, description = "")
  public Integer getExamRating() {
    return examRating;
  }

  public void setExamRating(Integer examRating) {
    this.examRating = examRating;
  }

  public UpdateTicketBean allowed(Boolean allowed) {
    this.allowed = allowed;
    return this;
  }

   /**
   * Get allowed
   * @return allowed
  **/
  @Schema(required = true, description = "")
  public Boolean isAllowed() {
    return allowed;
  }

  public void setAllowed(Boolean allowed) {
    this.allowed = allowed;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    UpdateTicketBean updateTicketBean = (UpdateTicketBean) o;
    return Objects.equals(this.id, updateTicketBean.id) &&
        Objects.equals(this.semesterRating, updateTicketBean.semesterRating) &&
        Objects.equals(this.examRating, updateTicketBean.examRating) &&
        Objects.equals(this.allowed, updateTicketBean.allowed);
  }

  @Override
  public int hashCode() {
    return Objects.hash(id, semesterRating, examRating, allowed);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class UpdateTicketBean {\n");
    
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    semesterRating: ").append(toIndentedString(semesterRating)).append("\n");
    sb.append("    examRating: ").append(toIndentedString(examRating)).append("\n");
    sb.append("    allowed: ").append(toIndentedString(allowed)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
